server {
    listen 80;
    resolver 127.0.0.11 valid=10s;

    location /rest/v1/ {
        set $upstream http://postgrest:3000;
        rewrite ^/rest/v1/(.*) /$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
